name: Docker Image CI

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file container/Dockerfile --tag ${{secrets.DOCKER_USER}}/jasen:latest

    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/jasen:latest
